# Generated by Django 5.1.2 on 2024-10-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0002_alter_ppicture_p_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ppicture",
            name="p_image",
            field=models.ImageField(upload_to="media"),
        ),
    ]
