# Generated by Django 5.1.2 on 2024-10-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0004_eventmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmodel",
            name="event_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
