# Generated by Django 5.1.2 on 2024-10-28 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0006_alter_eventmodel_event_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmodel",
            name="event_date",
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name="eventmodel",
            name="user",
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
