# Generated by Django 5.1.2 on 2024-11-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0009_bookeduser_user_alter_bookeduser_book_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCatorogy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catName", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="catevent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eventapp.eventcatorogy",
            ),
        ),
    ]
