# Generated by Django 5.1.2 on 2024-11-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0011_rename_catevent_eventmodel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcatorogy",
            name="catName",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
